---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8500
    targetPort: 8500
    nodePort: 30443
  selector:
    app: consul
    component: server
