---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  selector:
    app: currency
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: currency
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        "consul.hashicorp.com/connect-service-port": "9090"
        "consul.hashicorp.com/transparent-proxy-overwrite-probes": "false"
    spec:
      serviceAccountName: currency
      containers:
        - name: currency
          image: nicholasjackson/fake-service:v0.25.2
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 9090
              path: /ready
          livenessProbe:
            httpGet:
              port: 9090
              path: /health
          env:
            - name: LISTEN_ADDR
              value: 0.0.0.0:9090
            - name: NAME
              value: currency-v1
            - name: MESSAGE
              value: "2 USD for 1 GBP"
            - name: SERVER_TYPE
              value: "http"
          ports:
            - containerPort: 9090