---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        "consul.hashicorp.com/connect-service-port": "9090"
        consul.hashicorp.com/connect-service-upstreams: 'currency:9091'
        "consul.hashicorp.com/transparent-proxy-overwrite-probes": "false"
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.25.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 9090
              host: 127.0.0.1
              path: /health
          env:
            - name: UPSTREAM_URIS
              value: http://127.0.0.1:9091
            - name: LISTEN_ADDR
              value: 0.0.0.0:9090
            - name: NAME
              value: payments-v1
            - name: MESSAGE
              value: "PAYMENTS V1"
          ports:
            - containerPort: 9090