---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: 'payments:9091'
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.25.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 9090
              host: 127.0.0.1
              path: /health
          env:
            - name: UPSTREAM_URIS
              value: http://127.0.0.1:9091
            - name: LISTEN_ADDR
              value: 0.0.0.0:9090
            - name: NAME
              value: web
            - name: MESSAGE
              value: "Hello World"
            - name: SERVER_TYPE
              value: "http"
          ports:
            - containerPort: 9090